name: steamcity-iot-platform
region: ams
services:
- name: web
  source_dir: /
  github:
    repo: steamcity/steamcity_io
    branch: main
    deploy_on_push: true
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /api/health
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
static_sites: []